### ISSUE TITLE
Add anchorjs to post template

### ISSUE THREAD

**Issue by austinpray** [liveplant/about.liveplant.io#11]
https://github.com/bryanbraun/anchorjs

**Comment by nathanielks** [comment]
no. I completely disagree.

**Comment by austinpray** [comment]
lol at enlisted men questioning orders

**Comment by nathanielks** [comment]
![giphy-17](https://cloud.githubusercontent.com/assets/314009/7775016/e66d4254-0074-11e5-8420-6b642c25d6b7.gif)

**Comment by ChicagoGupta** [comment]
LOL

On Fri, May 22, 2015 at 11:23 AM, Nathaniel notifications@github.com
wrote:

> [image: giphy-17]
> https://cloud.githubusercontent.com/assets/314009/7775016/e66d4254-0074-11e5-8420-6b642c25d6b7.gif
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/liveplant/about.liveplant.io/issues/11#issuecomment-104703784
> .

## 

_Chirag Gupta_
Text: (214) 497-7771
Tweet: @ChicagoGupta http://twitter.com/@ChicagoGupta

Teaching yourself how to code https://gitter.im/BigDCode/Dallas?
Get out of the coffee shop + try coworking at NoD http://www.noddfw.com!
Sign up for North Dallas Startup Weekend here
http://www.eventbrite.com/e/north-dallas-startup-weekend-july-2015-tickets-14820888677
!

**Comment by ChicagoGupta** [comment]
Hey Y'all - 
 
 Welcome to the first edition of my monthly newsletter thing. Each month I'll publish a new one containing projects I'm working on, cool things going on in the Dallas startup community, and a song or two that I think you should check out.
 
 *Projects I'm working on*
 
 1. Raising $1,000 for Bold Idea <https://nachobirthday.com/campaign/id/814> [80% Funded, 24 hours to go!]
 
 2. Techweek Dallas <http://techweek.com/techweek-doubles-its-host-cities/> [Coming soon!]
 
 *Cool things*
 
 1. Article on Uber-esque startups in Dallas <http://www.dallasnews.com/business/small-business/20150804-doing-their-share.ece> [Dallas Morning News]
 
 2. International Coworking Week <http://coworkingweek.com/event-tickets/> [August 4th-10th]
 
 *Music*
 
 1. DotC <https://soundcloud.com/dawn-of-the-computer/computers-can-play-guitar-too> [Dallas-based glitch pop artist]
 
 2. Snarky Puppy <https://www.youtube.com/watch?v=L_XJ_s5IsQc> [Originally from Denton, TX]
 
 Keep it real,
 
 Chirag
 
 PS: To get in contact with me or to submit a link for my next newsletter, just shoot me a tweet at @ChicagoGupta <https://twitter.com/ChicagoGupta>.
Monkey Business by ChicagoGupta
http://tinyletter.com/ChicagoGupta
17290 Preston #300 Dallas, Texas 75252 USA

Sent to reply@reply.github.com
Unsubscribe: http://tinyletter.com/ChicagoGupta/unsub?c=741ee286-644f-4184-9644-be431fc17ded&m=chicagogupta-s-monthly-e-mail

Delivered by:
http://tinyletter.com
