### ISSUE TITLE
Create screencast walking through current codebase

### ISSUE THREAD

**Issue by austinpray** [liveplant/about.liveplant.io#20]
- [ ] record screencast
- [ ] upload to youtube
- [ ] create a post

**Comment by sanjaysasi19** [comment]
test comment

**Comment by CNRZ** [comment]
Can we mirror the Categories on Slack? So that it's easier to find the issues

**Comment by austinpray** [comment]
@CNRZ the channels are set up to mirror the repos. So server channels maps the the server repo etc. This issue is actually not in the correct repo. Good catch. 

moved to https://github.com/liveplant/liveplant-server/issues/16
